-- programa_academico
INSERT INTO programa_academico (id_programa, nombre_programa, id_departamento) VALUES
(1, 'Ingeniería de Software', 1),
(2, 'Ingeniería Eléctrica', 3),
(3, 'Ingeniería Mecánica', 2),
(4, 'Ingeniería Administrativa', 4),
(5, 'Ingeniería Industrial', 4),
(6, 'Ingeniería en Logística', 4),
(7, 'Ingeniería en Producción', 4),
(8, 'Ingeniería en Materiales', 4),
(9, 'Tecnología en Desarrollo de Software', 1),
(10, 'Tecnología en Gestión del Mantenimiento Aeronáutico', 2),
(11, 'Tecnología en Supervisión de Sistemas de Generación y Distribución de Energía Eléctrica', 3),
(12, 'Tecnología Eléctrica', 3),
(13, 'Tecnología en Sistemas Electromecánicos', 3),
(14, 'Tecnología en Mecánica Automotriz', 2),
(15, 'Técnica Profesional en Fabricación Digital e Impresión 3D', 2),
(16, 'Tecnología en Electrónica Industrial', 3),
(17, 'Profesional en Gestión del Diseño', 5),
(18, 'Profesional en Diseño Gráfico', 5),
(19, 'Tecnología en Diseño y Producción Gráfica', 5),
(20, 'Tecnología en Producción Industrial', 2),
(21, 'Tecnología en Sistemas Mecatrónicos', 1),
(22, 'Tecnología en Mecánica Industrial', 2),
(23, 'Profesional en Diseño de Vestuario', 2),
(24, 'Tecnología en Animación Digital', 5),
(25, 'Tecnología en Diseño y Producción de Vestuario', 5),
(26, 'Tecnología en Gestión Logística', 2);
